name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Overview card
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AnkitPorwal04
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_output: svg

      - name: Languages card
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AnkitPorwal04
          filename: metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          config_output: svg
